=pod

=head1 NAME

Mojolicious::Plugin::ClosedRedirect - Defend Open Redirect Attacks

=head1 SYNOPSIS

  # Check for Open Redirect Attack
  return if $c->closed_redirect_to('return_url');

  # Open Redirect attack discovered
  return $c->redirect_to('home');

  # Protection for open redirect_to

  $app->routes->route('/mypath')->name('mypath');

  $c->url_for('acct_login')->query([
    return_url => $c->signed_url_for('mytest')
  ]);

  # Redirect to valid url from $c->param('return_url')
  return if $c->closed_redirect_to('return_url');

  # Fails
  return $c->redirect_to('home');


=head1 DESCRIPTION

This plugin helps you to protect your users not to tap into a
L<http://cwe.mitre.org/data/definitions/601.html|OpenRedirect>
vulnerabilities by using signed URLs.

=head1 METHODS

=head2 register

=over 2

=item C<silent>

Accepts a boolean value, if users should not receive a notification
on redirect attacs. Defaults to not being silent.

=item C<token_length>

Set the length of the secret token to append to redirect locations.
Defaults to C<16>.

=item C<secret>

Pass the secret to be used to hash on redirect locations.
Defaults to the first application secret.

=back

All parameters can be set either on registration or as part
of the configuration file with the key C<ClosedRedirect>
(with the configuration file having the higher precedence).

=head1 HELPERS

=head1 BUGS and CAVEATS

The URLs are currently signed using SHA-1 and a free, prefixed secret
(with the default being the application secret).
There are known attacks to SHA-1, so this solution does not mean
you should not validate the URL further.

It is not possible to change session information after a successfull redirect,
so the normal way to deal with that is to have a fallback for non valid
closed redirects in a controller.

=head1 AVAILABILITY

  https://github.com/Akron/Mojolicious-Plugin-ClosedRedirect

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2016, L<Nils Diewald|http://nils-diewald.de/>.

This program is free software, you can redistribute it
and/or modify it under the terms of the Artistic License version 2.0.

=cut
